name: Ejercicio 3

on:
  push:
    branches:
      - main

jobs:
  generar-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Ejecutar el generador de código
        run: java -jar openapi-generator-cli.jar generate -i api.yaml -g python-flask -o ./openapi_server --skip-validate-spec
      - name: Empaquetar artefacto
        run: zip -r openapi_server.zip openapi_server
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
